all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
all_joints_names:
- snout
- right-forepaw
- left-forepaw
- right-hindpaw
- left-hindpaw
- tail-base
batch_size: 1
bottomheight: 400
crop: true
cropratio: 0.4
dataset: training-datasets\iteration-14\UnaugmentedDataSet_bottomup_clearSep21\bottomup_clear_hsu95shuffle1.mat
dataset_type: imgaug
display_iters: 1000
global_scale: 0.8
init_weights: C:\Users\alexa\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcutcore\pose_estimation_tensorflow\models\pretrained\resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
leftwidth: 400
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
max_input_size: 1500
metadataset: training-datasets\iteration-14\UnaugmentedDataSet_bottomup_clearSep21\Documentation_data-bottomup_clear_95shuffle1.pickle
min_input_size: 64
minsize: 100
mirror: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: resnet_50
num_joints: 6
pos_dist_thresh: 17
project_path: H:/bottomup_clear-hsu-2021-09-21
rightwidth: 400
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
topheight: 400
